name: tp2
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cupertino_list_tile: ^0.2.1
  firebase_auth:
  firebase_core:
 
  cloud_firestore: ^2.5.1
  intl: ^0.17.0
  firebase_messaging: ^10.0.9
  animations: ^2.0.1
  circle_list: ^1.0.5
 
   
  
  open_file: ^3.2.1
  photo_view: ^0.12.0
  image_picker:
  emoji_picker_flutter: ^1.0.6
  fluttertoast: ^8.0.8
  permission_handler: ^8.2.5
  file_picker: ^4.0.0
 
   

  just_audio: ^0.9.7
  percent_indicator: ^3.0.1
  record: ^3.0.0
  path_provider:
  firebase_storage: ^10.0.4
  dio: ^4.0.0
  
  http: ^0.13.4
  flutter_svg: ^1.0.3

  



  
 
  



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.4

 
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

#assets:
 # - assets/font/soleil.png
  uses-material-design: true

 
       # - asset: packages/awesome_package/fonts/Raleway-Regular.ttf
        #- asset: packages/awesome_package/fonts/Raleway-Italic.ttf
 
          
         




  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/fbook.png
   - assets/images/google.png
   - assets/logo/logo.png
   - assets/logo/Product_0.svg
   #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
   #fonts:
         #- asset: fonts/
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
